name: analysis
channels:
  - defaults
dependencies:
  - pandas=1.0.3
  - python=3.7
  - pyyaml=5.3.1
  - seaborn=0.11.1
  - numpy=1.18.1
  - yaml=0.1.7
  - click=7.1.2
  - matplotlib=3.2.2
  - scipy=1.5.2
  - scikit-bio
